defaults: &defaults
  adapter: mysql2
  username: root
  password: hello
  encoding: utf8

development:
  <<: *defaults
  database: mitnadvimlocal

test:
  <<: *defaults
  database: mitnadvimtest

production:
  <<: *defaults
  database: mitnadvimprod
